### ISSUE TITLE
xdebug

### ISSUE THREAD

**Issue by Decave** [avatarnewyork/dockerenv_apache#8]
We need to be able to use xdebug.

See [this tutorial](https://www.jetbrains.com/phpstorm/webhelp/configuring-xdebug.html) on how to integrate xdebug with PHPStorm. We can have xdebug disabled in by default in php.ini and enable it when we need to in .htaccess, but it still needs to be installed.

**Comment by jakraska** [comment]
Hey Pat,

I just wanted to bump this.  I've been working with xdebug a bit on some of my own projects, and i think it would be invaluable for a developer getting up to speed with some of our more complicated projects.  It has been a huge time saver for me personally.  

From my experience with xdebug i dont think the discussion in this thread is totally accurate.  You dont need to configure a remote PHP interperter or have access to the php executable.   Xdebug just needs to be installed and set to run in apache container.  The documentation in the initial link worked pretty well for me.  

The configuration in the IDE/editor is the trickiest part.  All the data goes over port 80 so we might even be ok using the hostnames and having them funneled through haproxy.  

Let me know if you want to spend some time (maybe next week?) working on this

**Comment by mrpatrick** [comment]
@Jesmaster @jakraska this is now working.  You can test a php53 version in your yml file using:

```yaml
image: 735711330dfb
```
 (instead of image: avatarnewyork/dockerenv-apache:php53)

Add your PC IP address to the variable below inside yml config and ensure you have your firewall disabled or leave port 9000 open on your PC:

```yaml
  environment:
    POSTFIX_HOSTNAME: dev.avatarnewyork.com
    POSTFIX_USER: postmaster@dev.avatarnewyork.com
    POSTFIX_PWD: 1e4b7fa82378fccccc7f5eacf80e902a
    XDEBUG_CLIENT_IP: 10.2.0.54
```

@jakraska might be good to have an overview / demo sometime on monday to see how to setup in phpstorm - was really helpful today.  Let me know if any issues and I'll role it into php53/php55 branches.  Thanks!

**Comment by jakraska** [comment]
@mrpatrick  Can we get this on 55 and merged into the normal image? i just confirmed it worked on jesses computer
